### PR TITLE
UPSTREAM: 47003: Remove duplicate errors from an aggregate error input.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr 

As the upstream PR https://github.com/kubernetes/kubernetes/pull/47003 is merged now, I have updated this PR.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
Do not merge yet as discussions are still going on in upstream kube PR.

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]

**Comment by smarterclayton** [comment]
```
# github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/errors
vendor/k8s.io/apimachinery/pkg/util/errors/errors_test.go:289: undefined: sort.Slice
vendor/k8s.io/apimachinery/pkg/util/errors/errors_test.go:293: undefined: sort.Slice
```

**Comment by aveshagarwal** [comment]
@smarterclayton looking.

**Comment by aveshagarwal** [comment]
Its happening because golang-1.7 does not understand sort.Slice whereas golang 1.8 does. Would it be ok to remove the unit test part and just have the main code?

**Comment by derekwaynecarr** [comment]
hmm, can we write go 1.7 style sort?  would make any other future backport requests not awful.

**Comment by aveshagarwal** [comment]
@derekwaynecarr I have updated this PR to make sorting work with go 1.7. I have put same upstream PR number: UPSTREAM: 47003 for these extra changes not in upstream kube.

**Comment by derekwaynecarr** [comment]
[merge][severity:blocker]
