### PR TITLE
use privileged  client in registry instead of user client when getting or creating signatures

### PR DESCRIPTION
**Pull request by mfojtik**
@csrwng 

Fixes: https://github.com/openshift/origin/issues/16349

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by mfojtik** [comment]
@csrwng i was wrong, this should imagestreamimage and not imagesignatures (imagesignatures does not have 'get' method, just create and delete), registry reads the signatures by querying the imagestreamimage

**Comment by runcom** [comment]
(for the record we need this fix in 3.7, but I see it's alpha so this should go in anyway /cc @mrunalp)

**Comment by csrwng** [comment]
I can confirm that this worked for me on a test cri-o cluster.

**Comment by mfojtik** [comment]
@liggitt || @enj the registry has an signature endpoint that you can use to get signature... this endpoint is proxying the signature data from openshift (signatures are stored in openshift images...).

I believe that granting the image-puller ability to get the imagestreamimage to serve the signature content is fine, but want to double-check if you can think of any security implications.

File: pkg/cmd/server/bootstrappolicy/policy.go [hunk 1]
```diff
@@ -533,6 +533,8 @@ func GetOpenshiftBootstrapClusterRoles() []rbac.ClusterRole {
 			Rules: []rbac.PolicyRule{
 				// pull images
 				rbac.NewRule("get").Groups(imageGroup, legacyImageGroup).Resources("imagestreams/layers").RuleOrDie(),
+				// read signatures
```
Comment (csrwng) [inline pkg/cmd/server/bootstrappolicy/policy.go]: you could just add "imagestreamimages" to the resources in the rule above this one.

Comment (mfojtik) [reply pkg/cmd/server/bootstrappolicy/policy.go]: wanted to make it clear why that rule is there

**Comment by enj** [comment]
> the registry has an signature endpoint that you can use to get signature... this endpoint is proxying the signature data from openshift (signatures are stored in openshift images...)

Er so what is preventing us from using that?

> I believe that granting the image-puller ability to get the imagestreamimage to serve the signature content is fine, but want to double-check if you can think of any security implications.

So what extra things can image-puller see/do with this permission?  I see that it can get the entire image, and not just the signatures.  I just do not have enough context to say how much extra information you are leaking to get access to the signature data.

@openshift/sig-security

File: pkg/cmd/server/bootstrappolicy/policy.go [hunk 2]
```diff
@@ -533,6 +533,8 @@ func GetOpenshiftBootstrapClusterRoles() []rbac.ClusterRole {
...
+				rbac.NewRule("get").Groups(imageGroup, legacyImageGroup).Resources("imagestreamimages").RuleOrDie(),
```
Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/policy.go]: this role is intended to grant permissions to call the registry endpoints. the registry is already authorizing getting signatures based on `get imagestreams/layers`, have the registry's signature endpoint get signatures from the API using the registry's client, not the user's

**Comment by mfojtik** [comment]
@liggitt tested locally and it is working (it returns empty signatures)

File: pkg/dockerregistry/server/signaturedispatcher.go [hunk 3]
```diff
@@ -82,9 +82,9 @@ func (s *signatureHandler) Put(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	client, ok := userClientFrom(s.ctx)
-	if !ok {
-		s.handleError(s.ctx, errcode.ErrorCodeUnknown.WithDetail("unable to get origin client"), w)
+	client, err := RegistryClientFrom(s.ctx).Client()
```
Comment (liggitt) [inline pkg/dockerregistry/server/signaturedispatcher.go]: before we let the user create signatures via the registry, verifyImageSignatureAccess ensures they have `create imagesignatures` permission, so using the user client here would work. I'm not actually sure whether the registry has `create imagesignatures` permission by default

File: pkg/dockerregistry/server/signaturedispatcher.go [hunk 4]
```diff
@@ -142,9 +142,9 @@ func (s *signatureHandler) Get(w http.ResponseWriter, req *http.Request) {
 		s.handleError(s.ctx, v2.ErrorCodeNameInvalid.WithDetail("missing image name or image ID"), w)
 		return
 	}
-	client, ok := userClientFrom(s.ctx)
-	if !ok {
-		s.handleError(s.ctx, errcode.ErrorCodeUnknown.WithDetail("unable to get origin client"), w)
+	client, err := RegistryClientFrom(s.ctx).Client()
```
Comment (liggitt) [inline pkg/dockerregistry/server/signaturedispatcher.go]: this looks fine

**Comment by liggitt** [comment]
switching to use the registry client on get looks fine. I'm not sure about the switch for put

**Comment by csrwng** [comment]
The code in its current state worked for me on cri-o

File: pkg/dockerregistry/server/signaturedispatcher.go [hunk 5]
```diff
@@ -142,9 +142,9 @@ func (s *signatureHandler) Get(w http.ResponseWriter, req *http.Request) {
...
+	if err != nil {
+		s.handleError(s.ctx, errcode.ErrorCodeUnknown.WithDetail(fmt.Sprintf("unable to get origin client", err)), w)
```
Comment (giuseppe) [inline pkg/dockerregistry/server/signaturedispatcher.go]: does the Sprintf miss the formatter?

File: pkg/dockerregistry/server/signaturedispatcher.go [hunk 6]
```diff
@@ -82,9 +82,9 @@ func (s *signatureHandler) Put(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	client, ok := userClientFrom(s.ctx)
-	if !ok {
-		s.handleError(s.ctx, errcode.ErrorCodeUnknown.WithDetail("unable to get origin client"), w)
+	client, err := RegistryClientFrom(s.ctx).Client()
+	if err != nil {
+		s.handleError(s.ctx, errcode.ErrorCodeUnknown.WithDetail(fmt.Sprintf("unable to get origin client", err)), w)
```
Comment (giuseppe) [inline pkg/dockerregistry/server/signaturedispatcher.go]: same here

**Comment by simo5** [comment]
Do we have a test that confirms user's that have no access to adding signtures actually fail to add them ?
If not we MUST (as in RFCs) have such a test as part of this PR.

File: pkg/dockerregistry/server/signaturedispatcher.go (hunk 5 above)
Comment (mfojtik) [reply pkg/dockerregistry/server/signaturedispatcher.go]: yes, good catch, thx

**Comment by mfojtik** [comment]
@simo5 we have signature extended test

**Comment by simo5** [comment]
@mfojtik excellent, thanks!

**Comment by kargakis** [comment]
This is breaking our batches 

/test all

**Comment by kargakis** [comment]
https://deck-ci.svc.ci.openshift.org/?type=batch

**Comment by liggitt** [comment]
```
# github.com/openshift/origin/pkg/dockerregistry/server
pkg/dockerregistry/server/signaturedispatcher.go:145: undefined: RegistryClientFrom
[ERROR] PID 1623: hack/lib/build/binaries.sh:228: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags="${local_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 2.
```

**Comment by mfojtik** [comment]
@dmage seems like this was broken by https://github.com/openshift/origin/pull/15796 can you please provide an advise how can one get privileged client in signaturedispatcher?

**Comment by liggitt** [comment]
pass registryClient to RegisterSignatureHandlers and hold a reference to it in the handler, rather than retrieve it from the context

**Comment by mfojtik** [comment]
@liggitt yeah,  already working on that...

**Comment by dmage** [comment]
@mfojtik make RegisterSignatureHandler and SignatureDispatcher to be methods of (app *App). That will allow you use app.registryClient in SignatureDispatcher. You can put app.registryClient into signatureHandler.

**Comment by mfojtik** [comment]
@dmage done, unfortunately i have to plumb the unit tests as well... puzzled how they ever worked as the signaturedispatcher use the clientset and not openshift client.

**Comment by dmage** [comment]
@mfojtik don't forget to push your changes :)

**Comment by mfojtik** [comment]
@dmage once they compile...

**Comment by mfojtik** [comment]
@dmage ok, running out of options, but i'm getting 	signaturedispatcher_test.go:113: unexpected response status: 401 when running the `TestSignatureGet`, any clues?

**Comment by mfojtik** [comment]
sunday pebkac, nvmd.

File: pkg/dockerregistry/server/signaturedispatcher_test.go [hunk 7]
```diff
@@ -57,6 +57,8 @@ func TestSignatureGet(t *testing.T) {
 		t.Fatal(err)
 	}
 
+	os.Setenv("OPENSHIFT_DEFAULT_REGISTRY", "localhost:5000")
```
Comment (mfojtik) [inline pkg/dockerregistry/server/signaturedispatcher_test.go]: @dmage for some strange reasons this is needed (at least on OSX) otherwise the NewApp() will fail... we should make this a field in openshift middleware config

Comment (liggitt) [reply pkg/dockerregistry/server/signaturedispatcher_test.go]: Can you fix this as part of this PR? This is pretty wonky

Comment (dmage) [reply pkg/dockerregistry/server/signaturedispatcher_test.go]: @mfojtik yes, configuration check is moved to the app constructor. Adding a field in config will introduce yet another one environment variable for this value (we already have DEFAULT_REGISTRY_URL and OPENSHIFT_DEFAULT_REGISTRY). But I like this idea.

Comment (mfojtik) [reply pkg/dockerregistry/server/signaturedispatcher_test.go]: fixed in a separate commit

File: pkg/dockerregistry/server/repositoryconfig.go [hunk 8]
```diff
@@ -74,6 +78,11 @@ func newRepositoryConfig(ctx context.Context, options map[string]interface{}) (r
 	} else {
 		context.GetLogger(ctx).Infof("DEPRECATED: %q is deprecated, use the %q instead", DockerRegistryURLEnvVar, OpenShiftDefaultRegistryEnvVar)
 	}
+	rc.registryAddr, err = getStringOption(DockerRegistryURLEnvVarOption, "dockerregistryurl", rc.registryAddr, options)
```
Comment (dmage) [inline pkg/dockerregistry/server/repositoryconfig.go]: Only if rc.registryAddr has not filled yet.

File: pkg/dockerregistry/server/repositoryconfig.go [hunk 9]
```diff
@@ -15,6 +15,10 @@ const (
 	// DEPRECATED: Use the OPENSHIFT_DEFAULT_REGISTRY instead.
 	DockerRegistryURLEnvVar = "DOCKER_REGISTRY_URL"
 
+	// DockerRegistryURLEnvVarOption is an optional environment that overrides the
+	// DOCKER_REGISTRY_URL.
+	DockerRegistryURLEnvVarOption = "REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_DOCKER_REGISTRY_URL"
```
Comment (dmage) [inline pkg/dockerregistry/server/repositoryconfig.go]: s/DOCKER_REGISTRY_URL/DOCKERREGISTRYURL/

File: pkg/dockerregistry/server/signaturedispatcher_test.go [hunk 10]
```diff
@@ -79,9 +78,9 @@ func TestSignatureGet(t *testing.T) {
 			},
 		},
 		Middleware: map[string][]configuration.Middleware{
-			"registry":   {{Name: "openshift"}},
-			"repository": {{Name: "openshift"}},
-			"storage":    {{Name: "openshift"}},
+			"registry":   {{Name: "openshift", Options: configuration.Parameters{"dockerregistryurl": "localhost:5000"}}},
+			"repository": {{Name: "openshift", Options: configuration.Parameters{"dockerregistryurl": "localhost:5000"}}},
+			"storage":    {{Name: "openshift", Options: configuration.Parameters{"dockerregistryurl": "localhost:5000"}}},
```
Comment (dmage) [inline pkg/dockerregistry/server/signaturedispatcher_test.go]: this option is only for the repository middleware

File: pkg/dockerregistry/server/repositoryconfig.go (hunk 8 above)
Comment (mfojtik) [reply pkg/dockerregistry/server/repositoryconfig.go]: i would say that having this in configuration file overrides all env vars?

File: pkg/dockerregistry/server/repositoryconfig.go (hunk 9 above)
Comment (liggitt) [reply pkg/dockerregistry/server/repositoryconfig.go]: why do we need a second envvar for this?

File: pkg/dockerregistry/server/repositoryconfig.go (hunk 8 above)
Comment (dmage) [reply pkg/dockerregistry/server/repositoryconfig.go]: Your code erases previous value no matter what. And environment variables usually overrides values in a config file.

**Comment by mfojtik** [comment]
@dmage comments addressed
