### ISSUE TITLE
Install dnsmasq configuration fails during conformance runs

### ISSUE THREAD

**Issue by gabemontero** [openshift/origin#15874]
See https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4432

```

TASK [openshift_node_dnsmasq : Install dnsmasq configuration] ******************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_node_dnsmasq/tasks/main.yml:28
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-08-18 20:56:16.634049", 
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'"
}
 [WARNING]: Could not create retry file '/usr/share/ansible/openshift-
ansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:
u'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'
```

**Comment by tnozicka** [comment]
failed 3 times in row in https://github.com/openshift/origin/pull/15868#issuecomment-323680760

last log https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4470/testReport/(root)/Configure%20nodes/_localhost__openshift_node_dnsmasq___Install_dnsmasq_configuration/

**Comment by tnozicka** [comment]
again in https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_conformance_install_update/4478/testReport/junit/(root)/Configure%20nodes/_localhost__openshift_node_dnsmasq___Install_dnsmasq_configuration/

For the 5th time in row. This is blocking tests.

**Comment by mfojtik** [comment]
@jhadvig seems like @stevekuznetsov is out, we need your superpowers.

**Comment by tnozicka** [comment]
seems like it's fixed in master, just not used in CI
https://github.com/openshift/openshift-ansible/pull/5142#issuecomment-323730419

**Comment by jhadvig** [comment]
Issue has been fixed in https://github.com/openshift/aos-cd-jobs/pull/578
