### PR TITLE
switch image api to use SAR client, not registry

### PR DESCRIPTION
**Pull request by deads2k**
Use a normal client for running SAR checks.

@mfojtik @soltysh this is on the path to splitting out the storage for the image APIs

### CODE REVIEW

File: pkg/image/registry/imagestream/strategy.go [hunk 1]
```diff
@@ -462,21 +463,24 @@ func (v *TagVerifier) Verify(old, stream *imageapi.ImageStream, user user.Info)
...
-				Verb:         "get",
-				Group:        imageapi.LegacyGroupName,
-				Resource:     "imagestreams/layers",
-				ResourceName: streamName,
+		subjectAccessReview := authorizationutil.AddUserToSAR(user, &authorizationapi.SubjectAccessReview{
+			Spec: authorizationapi.SubjectAccessReviewSpec{
+				ResourceAttributes: &authorizationapi.ResourceAttributes{
+					Namespace:   tagRef.From.Namespace,
+					Verb:        "get",
+					Group:       imageapi.GroupName,
```
Comment (deads2k) [inline pkg/image/registry/imagestream/strategy.go]: I change this.  Looks like a typo before.  This groupified check should also have permission.

Comment (mfojtik) [reply pkg/image/registry/imagestream/strategy.go]: does empty group vs. image.openshift.io matters here? guess we need support both

Comment (deads2k) [reply pkg/image/registry/imagestream/strategy.go]: > does empty group vs. image.openshift.io matters here? guess we need support both

It's a server back to itself call, the roles will be reconciled.  I think this usage is correct.

Comment (mfojtik) [reply pkg/image/registry/imagestream/strategy.go]: thx for clarification :)

**Comment by kargakis** [comment]
/lgtm cancel

This PR has been breaking our batch jobs since yesterday because in conjuction with https://github.com/openshift/origin/pull/16147, it produces a compilation error.

/test all

**Comment by deads2k** [comment]
combined in https://github.com/openshift/origin/pull/16170/commits
