### ISSUE TITLE
cmd/oc wants gssapi/gssapi.h

### ISSUE THREAD

**Issue by dmage** [openshift/origin#17621]
```
$ ./hack/build-go.sh cmd/oc
++ Building go targets for linux/amd64: cmd/oc
# github.com/openshift/origin/vendor/github.com/apcera/gssapi
vendor/github.com/apcera/gssapi/buffer.go:9:27: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
```
/cc @mfojtik

**Comment by mfojtik** [comment]
@deads2k seems like this was introduced by glide bump.

**Comment by deads2k** [comment]
I don't think that's new. Came in ages ago when we added support, right?

**Comment by dmage** [comment]
No,

```
~/src/github.com/openshift/origin (master)$ git checkout v3.7.0
~/src/github.com/openshift/origin ((v3.7.0))$ ./hack/build-go.sh cmd/oc
++ Building go targets for linux/amd64: cmd/oc
[INFO] hack/build-go.sh exited with code 0 after 00h 01m 10s
~/src/github.com/openshift/origin ((v3.7.0))$ git checkout master
~/src/github.com/openshift/origin (master)$ ./hack/build-go.sh cmd/oc
++ Building go targets for linux/amd64: cmd/oc
# github.com/openshift/origin/vendor/github.com/apcera/gssapi
vendor/github.com/apcera/gssapi/buffer.go:9:27: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
```

> $ git bisect start master v3.7.0
> $ git bisect run ./hack/build-go.sh cmd/oc
> 1a8b960ce025a09f5e3e244c0836c9850c9ce3ca is the first bad commit

**Comment by enj** [comment]
Seems like we went from requiring GSSAPI only when the flags are set to always requiring it?  No sure I care too much, but @stevekuznetsov or @smarterclayton will probably have some thoughts.

cc @simo5

**Comment by stevekuznetsov** [comment]
Yeah, the linked commit from @smarterclayton does change build flags. I'd expect that to be the issue.

**Comment by pmorie** [comment]
You can work around this by installing the `krb5-devel` package.
