### ISSUE TITLE
logging-fluentd pods failing to start after upgrading from 3.7 to 3.9

### ISSUE THREAD

**Issue by benscottub** [openshift/origin#20534]
logging-fluentd pods are failing to start after upgrading Origin from 3.7 to 3.9. The ansible script appeared to complete successfully without errors or warnings. This is the error that the fluentd pods are reporting (This is also the only line that shows up in the pod logs):
```
-e:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

##### Version
```
[bens@osndev1 ~]$ openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
[bens@osndev1 ~]$ oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

##### Steps To Reproduce
1) run the config.yml playbook to upgrade logging to 3.9.
2) observe that all of the logging-fluentd-XXXXXX pods are in Crash Loop Back-off state
the elastic search data master pod, the curator pod and the kibana pod are all running successfully.

We have tried manually deleting the pods so that they refresh themselves, as well as completely deleting the logging project and re-running the config.yml playbook to rebuild the logging with the same result.

##### Current Result
The logging-fluentd pods are failing to start.
##### Expected Result
All of the logging pods start and run successfully.
##### Additional Information

Please let me know what additional diagnostic information would be helpful. The error message is very sparse and has not given much to go on. Thank you.

**Comment by jwforres** [comment]
@openshift/sig-logging

**Comment by nhosoi** [comment]
Do you see anything unusual in this output especially in the Events section?
oc describe $(oc get pod -l component=fluentd -o name)

Also, you'd get quicker response if you use this issues since logging-fluentd belongs to origin-aggregated-logging.
https://github.com/openshift/origin-aggregated-logging/issues
Thanks.
