### PR TITLE
Add Back node-bootstrapper Service Account creation

### LINKED ISSUE #15869: node-bootstrapper service account does not exist
When going to 3.7 the node-bootstrapper service account is missing.

##### Version
[root@ip-172-31-48-185 ~]# oc version
oc v3.7.0-0.27.0
kubernetes v1.7.0+695f48a16f
openshift v3.7.0-0.27.0
kubernetes v1.7.0+695f48a16f

##### Steps To Reproduce
1. Install a 3.7.0-0.27.0
2. Verify node-bootstrapper service account does not exist

##### Current Result
No exist!

##### Expected Result
Exists
##### Additional Information
This was working with 3.6.171.  Something probably regressed a patch or something.  Please put it back so I can test scale group configurations with node bootstrapping!

atomic-openshift-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
tuned-profiles-atomic-openshift-node-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-excluder-3.7.0-0.27.0.git.0.071dcde.el7.noarch
atomic-openshift-clients-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-master-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-node-3.7.0-0.27.0.git.0.071dcde.el7.x86_64
atomic-openshift-docker-excluder-3.7.0-0.27.0.git.0.071dcde.el7.noarch

### PR DESCRIPTION
**Pull request by tiran**
This was recently dropped together with some refactoring for Controller
Roles bootstrapping.

Fixes #15869

@simo5's PR #15890 + test fix

@openshift/sig-security

### CODE REVIEW

**Comment by tiran** [comment]
ci/openshift-jenkins/extended_conformance_install_update is caused by a problem in openshift-ansible, see https://github.com/openshift/openshift-ansible/issues/5146

```
TASK [openshift_node_dnsmasq : Install dnsmasq configuration] ******************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_node_dnsmasq/tasks/main.yml:28
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "generated_timestamp": "2017-08-22 06:38:56.567080", 
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'dns_ip'"
}
``

File: pkg/cmd/server/bootstrappolicy/constants.go [hunk 1]
```diff
@@ -28,6 +28,8 @@ const (
 	// This should remain in the default role bindings for the NodeAdmin role
 	LegacyMasterKubeletAdminClientUsername = "system:master"
 	MasterKubeletAdminClientUsername       = "system:openshift-node-admin"
+
+	InfraNodeBootstrapServiceAccountName = "system:" + NodeBootstrapRoleName
```
Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/constants.go]: this is not the name of the service account... this belongs more in the `controller_policy.go` file than here... it's more akin to the template service broker

Comment (tiran) [inline pkg/cmd/server/bootstrappolicy/constants.go]: k8s defines the name as ``apiconfig.NodeBootstrapperClusterRoleName``. Can we use the name from ``k8s.io/kubernetes/cmd/kubeadm/app/phases/apiconfig``?

Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/constants.go]: no, don't reference code within kubeadm

Comment (simo5) [inline pkg/cmd/server/bootstrappolicy/constants.go]: @liggitt what do you mean with "this is not the name of the service account" ?

Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/constants.go]: the constant is `InfraNodeBootstrapServiceAccountName`, but `system:node-bootstrapper` is not the name of the service account

Comment (simo5) [inline pkg/cmd/server/bootstrappolicy/constants.go]: @liggitt thanks sorted out with @enj that in restroing the names I ended up reversing the role and the account name ... @tiran is going to fix it

File: pkg/cmd/server/bootstrappolicy/constants.go [hunk 2]
```diff
@@ -28,6 +28,8 @@ const (
 	// This should remain in the default role bindings for the NodeAdmin role
 	LegacyMasterKubeletAdminClientUsername = "system:master"
 	MasterKubeletAdminClientUsername       = "system:openshift-node-admin"
+
+	InfraNodeBootstrapServiceAccountName = "node-bootstrapper"
```
Comment (simo5) [inline pkg/cmd/server/bootstrappolicy/constants.go]: @enj indeed the controller_policy file now risk becoming a kitchen sink, feels wrong to me.
That is why I put the constants in ... guess what? "constants.go"

File: pkg/cmd/server/bootstrappolicy/policy.go [hunk 3]
```diff
@@ -993,6 +993,9 @@ func GetOpenshiftBootstrapClusterRoleBindings() []rbac.ClusterRoleBinding {
 		newOriginClusterBinding(BuildStrategyJenkinsPipelineRoleBindingName, BuildStrategyJenkinsPipelineRoleName).
 			Groups(AuthenticatedGroup).
 			BindingOrDie(),
+		rbac.NewClusterBinding(NodeBootstrapRoleName).
```
Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/policy.go]: it certainly needs a separating comment, not be grouped with the build strategies roles

**Comment by enj** [comment]
@tiran please move the `const`s to controller policy, I will handle any clean up in #15937

**Comment by enj** [comment]
/lgtm

I will figure out homes for the `const`'s that make people happy, or at least equally unhappy.
